



export const GET_ALL_BLOG_REQUEST = "GET_ALL_BLOG_REQUEST"
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS"
export const GET_ALL_BLOG_FAILURE = "GET_ALL_BLOG_FAILURE"

// export const LOGIN_REQUEST = "LOGIN_REQUEST"
// export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
// export const LOGIN_FAILURE = "LOGIN_FAILURE"