



export const GET_ALL_BLOG_REQUEST = "GET_ALL_BLOG_REQUEST"
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS"
export const GET_ALL_BLOG_FAILURE = "GET_ALL_BLOG_FAILURE"


export const GET_USER_BLOG_REQUEST = "GET_USER_BLOG_REQUEST"
export const GET_USER_BLOG_SUCCESS = "GET_USER_BLOG_SUCCESS"
export const GET_USER_BLOG_FAILURE = "GET_USER_BLOG_FAILURE"